name: Build Starting Goalies Binary

on:
    push:
        paths:
            - "cmd/startingGoalies/**"
            - "pkg/**"
            - "go.mod"
            - "go.sum"
            - ".github/workflows/build-binary.yml" # Trigger when this workflow is added
    pull_request:
        paths:
            - "cmd/startingGoalies/**"
            - "pkg/**"
            - "go.mod"
            - "go.sum"
    workflow_dispatch:

jobs:
    build-binary:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24"
                  cache: true

            - name: Download dependencies
              run: go mod download

            - name: Build binary
              run: |
                  cd cmd/startingGoalies
                  go build -o goalies main.go

            - name: Upload binary as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: starting-goalies-binary
                  path: cmd/startingGoalies/goalies
                  retention-days: 30

            - name: Cache binary for scheduler workflow
              uses: actions/cache/save@v4
              with:
                  path: cmd/startingGoalies/goalies
                  key: goalies-binary-${{ github.sha }}-${{ hashFiles('**/*.go', 'go.sum', 'go.mod') }}
