name: Starting Goalies Scheduler

on:
  schedule:
    - cron: "45 0-2,15-23 * * *"
  repository_dispatch:
    types: [run-goalies]
  workflow_dispatch:

env:
  SECRETS: ${{ secrets.SECRETS }}

jobs:
  run-starting-goalies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Create .env file from JSON secret
        run: |
          echo '${{ secrets.SECRETS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env

      - name: Download dependencies
        run: go mod download

      - name: Cache compiled binary
        uses: actions/cache@v4
        id: binary-cache
        with:
          path: cmd/startingGoalies/goalies
          key: ${{ runner.os }}-binary-${{ hashFiles('**/*.go', 'go.sum', 'go.mod') }}

      - name: Build binary (compile once, run fast)
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          cd cmd/startingGoalies
          go build -o goalies main.go

      - name: Run starting goalies program
        run: |
          cd cmd/startingGoalies
          ./goalies

      - name: Upload logs (optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: goalies-logs
          path: cmd/startingGoalies/logs.log
          retention-days: 7
