name: Starting Goalies Scheduler

on:
  schedule:
    - cron: "45 0-2,15-23 * * *"
  repository_dispatch:
    types: [run-goalies]
  workflow_dispatch:

env:
  SECRETS: ${{ secrets.SECRETS }}

jobs:
  run-starting-goalies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Create .env file from JSON secret
        run: |
          echo '${{ secrets.SECRETS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env

      - name: Try to restore cached binary
        uses: actions/cache/restore@v4
        id: binary-cache
        with:
          path: cmd/startingGoalies/goalies
          key: goalies-binary-${{ github.sha }}-${{ hashFiles('**/*.go', 'go.sum', 'go.mod') }}
          restore-keys: |
            goalies-binary-${{ github.sha }}-
            goalies-binary-

      - name: Download pre-built binary (fallback)
        if: steps.binary-cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: starting-goalies-binary
          path: cmd/startingGoalies/
        continue-on-error: true

      - name: Build binary (final fallback)
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          cd cmd/startingGoalies
          if [ ! -f goalies ]; then
            echo "No cached or pre-built binary found, building from source..."
            go mod download
            go build -o goalies main.go
          else
            echo "Using downloaded pre-built binary"
            chmod +x goalies
          fi

      - name: Run starting goalies program
        run: |
          cd cmd/startingGoalies
          chmod +x goalies
          ./goalies

      - name: Upload logs (optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: goalies-logs
          path: cmd/startingGoalies/logs.log
          retention-days: 7
