name: Test Scheduler

on:
  schedule:
    # Run every 3 minutes for testing
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        run: |
          echo "Test workflow ran at: $(date)"
          echo "This is just a test to verify GitHub Actions scheduling works"
